"""Creacion de tablas: departamentos y puestos. Update: empleados

Revision ID: ceff8f3ac950
Revises: 5c76e88f3453
Create Date: 2024-10-06 01:12:21.045089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceff8f3ac950'
down_revision = '5c76e88f3453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    op.create_table('puestos',
    sa.Column('id_puesto', sa.Integer(), nullable=False),
    sa.Column('puesto', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_puesto')
    )
    op.create_table('empleados',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('apellido', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=False),
    sa.Column('fechaNacimiento', sa.Date(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id_departamento'], ),
    sa.ForeignKeyConstraint(['puesto_id'], ['puestos.id_puesto'], ),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    op.drop_table('empleado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='empleado_pkey')
    )
    op.drop_table('empleados')
    op.drop_table('puestos')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
